### PR TITLE
Fix typos and missing quotes in input.

### PR DESCRIPTION
**Pull request by jaworek**
Hi,
I noticed a couple of typos.
I downloaded this extension from Firefox store and when I click "Go" button nothing happens.
Maybe it's because quotes in class in 'input' was missing.
If it will not fix the problem, I will create separate issue for it.

### CODE REVIEW

**Comment by kodxana** [comment]
Did you gave it input file first and then press Go :)

**Comment by jaworek** [comment]
Yep

**Comment by kodxana** [comment]
Intresting I tested it on firefox and it worked perfectly fine. Tested the build I uploaded to firefox store.

**Comment by kodxana** [comment]
Wanna get in call so you can show me the problem? If yes I'm waiting at https://talk.allaboutlbc.com/GithubMadiator

**Pull request closed without merging**
